config:
  target: 'http://127.0.0.1:3000'
  phases:
    - duration: 30
      arrivalRate: 10
      name: "Warm-up"

    - duration: 60
      arrivalRate: 20
      rampTo: 80
      name: "Ramp-up"

    - duration: 180
      arrivalRate: 100
      rampTo: 150
      name: "Sustained Load"

  variables:
    receiverId:
      - "user1.test.near"
      - "user2.test.near"
      - "user3.test.near"
      - "alice.test.near"
      - "bob.test.near"

    amount:
      - "1000000000000000000000000"
      - "5000000000000000000000000"
      - "10000000000000000000000000"

  defaults:
    headers:
      Content-Type: 'application/json'

scenarios:
  - name: "Sandbox FT Transfer Load Test"
    weight: 80
    flow:
      - post:
          url: "/send-ft"
          json:
            receiverId: "{{ receiverId }}"
            amount: "{{ amount }}"
            memo: "Sandbox load test {{ $timestamp }}"
          expect:
            - statusCode: [200, 400, 500]

  - name: "Sandbox Health Check"
    weight: 20
    flow:
      - get:
          url: "/health"
          expect:
            - statusCode: 200