name: Sandbox Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 18 * * 1' # Every Tuesday at 01:00 WIB (Monday 18:00 UTC)

concurrency:
  group: sandbox-benchmark
  cancel-in-progress: false

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Ensure benchmark scripts are executable
        run: |
          chmod +x testing/test-complete-pipeline.sh
          chmod +x testing/artillery/run-artillery-test.sh

      - name: Run sandbox benchmark pipeline
        env:
          CI: 'true'
          TEST_DURATION: '1100'
          MAX_TPS: '180'
          SANDBOX_HEADROOM_PERCENT: '85'
          SANDBOX_USE_CLUSTER: '1'
          CLUSTER_WORKERS: '4'
          ARTILLERY_PROFILE: 'benchmark-sandbox.yml'
          SANDBOX_MAX_IN_FLIGHT_PER_KEY: '8'
        run: ./testing/test-complete-pipeline.sh

      - name: Summarize Artillery results
        if: always()
        run: |
          node scripts/report-benchmark.mjs >> "$GITHUB_STEP_SUMMARY"

      - name: Upload benchmark artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sandbox-benchmark-artifacts
          path: |
            sandbox.log
            api.log
            service*.log
            testing/artillery/.last-artillery-run.log
            testing/artillery/artillery-results-sandbox-*.json
            testing/artillery/*.yml
          if-no-files-found: ignore
