name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build (tsc)
        run: npm run build

      - name: Type check
        run: npm run typecheck

      - name: Frontend smoke tests
        run: npm run test:frontend

      - name: Sandbox integration tests
        env:
          CI: 'true'
        run: npm run test:sandbox

      - name: Security audit (critical only)
        run: npm run security

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload sandbox logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: sandbox-artifacts
          path: |
            sandbox.log
            service*.log
            test-results
          if-no-files-found: ignore
