name: Sandbox Integration (CI)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *' # Daily at 01:00 WIB
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.github/workflows/sandbox-integration.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.github/workflows/sandbox-integration.yml'

jobs:
  sandbox-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run sandbox integration tests
        env:
          CI: 'true'
        run: npm run test:sandbox
